<?php

$finder = PhpCsFixer\Finder::create()
	->in(__DIR__ . '/src')
	->in(__DIR__ . '/public');

$config = new PhpCsFixer\Config();
return $config
	->setRules([
		'@PSR12' => true,
		'@PHP81Migration' => true,
		// additional rules
		'align_multiline_comment' => true,
		'array_indentation' => true,
		'array_syntax' => ['syntax' => 'short'],
		'backtick_to_shell_exec' => true,
		'binary_operator_spaces' => true,
		'braces' => ['allow_single_line_anonymous_class_with_empty_body' => true, 'allow_single_line_closure' => true],
		'cast_spaces' => true,
		'class_attributes_separation' => ['elements' => ['method' => 'one']],
		'class_definition' => ['single_line' => true],
		'clean_namespace' => true,
		'combine_consecutive_issets' => true,
		'combine_consecutive_unsets' => true,
		'concat_space' => ['spacing' => 'one'],
		'echo_tag_syntax' => ['format' => 'short', 'shorten_simple_statements_only' => true],
		'empty_loop_body' => ['style' => 'braces'],
		'escape_implicit_backslashes' => true,
		'explicit_indirect_variable' => true,
		'explicit_string_variable' => true,
		'fully_qualified_strict_types' => true,
		'function_typehint_space' => true,
		'include' => true,
		'increment_style' => ['style' => 'post'],
		'lambda_not_used_import' => true,
		'linebreak_after_opening_tag' => true,
		'magic_constant_casing' => true,
		'magic_method_casing' => true,
		'method_argument_space' => ['on_multiline' => 'ignore'],
		'native_function_casing' => true,
		'native_function_type_declaration_casing' => true,
		'no_alias_language_construct_call' => true,
		'no_binary_string' => true,
		'no_blank_lines_after_phpdoc' => true,
		'no_empty_comment' => true,
		'no_empty_phpdoc' => true,
		'no_empty_statement' => true,
		'no_leading_namespace_whitespace' => true,
		'no_mixed_echo_print' => ['use' => 'print'],
		'no_null_property_initialization' => true,
		'no_multiline_whitespace_around_double_arrow' => true,
		'no_short_bool_cast' => true,
		'no_singleline_whitespace_before_semicolons' => true,
		'no_spaces_around_offset' => true,
		'no_superfluous_elseif' => true,
		'no_trailing_comma_in_list_call' => true,
		'no_trailing_comma_in_singleline_array' => true,
		'no_unneeded_control_parentheses' => ['statements' => ['break', 'clone', 'continue', 'echo_print', 'return', 'switch_case', 'yield', 'yield_from']],
		'no_unneeded_curly_braces' => ['namespaces' => true],
		'no_unset_cast' => true,
		'no_unused_imports' => true,
		'no_useless_else' => true,
		'no_useless_return' => true,
		'no_whitespace_before_comma_in_array' => true,
		'normalize_index_brace' => true,
		'object_operator_without_whitespace' => true,
		'ordered_class_elements' => true,
		'ordered_imports' => true,
		'protected_to_private' => true,
		'return_assignment' => true,
		'simple_to_complex_string_variable' => true,
		'single_class_element_per_statement' => true,
		'single_line_comment_style' => true,
		'single_line_throw' => true,
		'single_quote' => true,
		'single_space_after_construct' => true,
		'space_after_semicolon' => ['remove_in_empty_for_expressions' => true],
		'standardize_increment' => true,
		'standardize_not_equals' => true,
		'switch_continue_to_break' => true,
		'trailing_comma_in_multiline' => true,
		'trim_array_spaces' => true,
		'types_spaces' => true,
		'unary_operator_spaces' => true,
		'whitespace_after_comma_in_array' => true,
		'yoda_style' => ['equal' => false, 'identical' => false, 'less_and_greater' => false],
		// risky
		'no_unreachable_default_argument_value' => true,
		'native_function_invocation' => ['include' => ['@compiler_optimized'], 'scope' => 'namespaced', 'strict' => true],
	])
	->setIndent("\t")
	->setFinder($finder);
